# Generated by Django 4.2.19 on 2025-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
