# Generated by Django 4.2.19 on 2025-02-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=15, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(max_length=50)),
                ('assurance', models.DateField()),
                ('controle_technique', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=200)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camions.camion')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employes.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camions.camion')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pieces_remplacees', models.TextField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camions.camion')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Carburant', 'Carburant'), ('Peages', 'Peages'), ('Reparations', 'Reparations'), ('Salaires', 'Salaires')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camions.camion')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employes.employe')),
            ],
        ),
    ]
